### ISSUE TITLE
Convert to library cookbook? Refactor into custom resources?

### ISSUE THREAD

**Issue by jeffbyrnes** [djoos-cookbooks/newrelic#247]
@djoos I wonder if the cookbook should be updated to better take advantage of Chef’s resources, introduced in Chef 12.5.

Two things I’d offer to help out with:
1. Refactor the LWRPs into Custom Resources
   - No more resources & providers!
   - Abstract some logic out of the recipes, into the resources themselves (e.g., the `license NewRelic.application_monitoring_license node` bit on almost every resource)
2. Drop the huge mess of attributes on every recipe
   - Rather than use attributes, just use the default value mechanism available on the properties (which you are already doing, so the attributes are already unnecessary)
   - Instead, opt for a mechanism that trusts the operator understands how to configure the agent in question
     - For any config values for the `newrelic.yml` that are required, (e.g., the license, the app name) keep those as top-level properties on a resource & require them
     - Otherwise, pass in the values for the `newrelic.yml` as a hash, and convert it 1:1 to YAML
       - This avoids the need to keep up with any changes to the `newrelic.yml` in a template

So you’d end up with a resource like this:

``` ruby
default_action :install

property :version,              default: 'latest'
property :install_dir,          default: '/opt/newrelic/java'
property :agent_action,         default: 'install'
property :execute_agent_action, default: true
property :app_location,         default: nil
property :app_user,             default: 'newrelic'
property :app_group,            default: 'newrelic'

# The following are combined & converted to YAML for the newrelic.yml config file
property :license,              default: NewRelic.application_monitoring_license(node)
property :app_name,             String,             required: true
property :config,               Hash,               required: true

action :install do
  config['common']['license_key'] = license

  file "#{install_dir}/newrelic.yml" do
    owner   app_user
    group   app_group
    content yaml_config(config) # github.com/sczizzo/magic-cookbook#yaml
  end

  # etc etc
end
```

And you’d use it like so:

``` ruby
newrelic_java_agent 'install' do
  version      '3.28.0'
  install_dir  '/usr/share/jetty/newrelic'
  app_location '/usr/share/jetty'
  license      'my-license-key'
  app_name     'My Great Java App'
end
```

**Comment by djoos** [comment]
Hi @jeffbyrnes,

I really like the sound of this and would like to consider it for version 3.x of the cookbook, however: I'm interested in having a deeper look at how much we would be able to do already without breaking BC and basically start shipping increments in 2.x?

Thanks in advance!
David

**Comment by jeffbyrnes** [comment]
@djoos sorry for the silence; I think, owing to the very nature of this sort of refactor, each of the changes I outline above would be something I’d consider breaking. Dropping attributes would break most implementations, and even keeping the attributes, but refactoring things into custom resources is potentially breaking.

I’ve done a few of these recently, and am in the middle of one for the `zookeeper` cookbook (see evertrue/zookeeper-cookbook#175).

**Comment by Sapr0** [comment]
Can we bump this work please !?
Some cookbook owners release two versions of a cookbook till the transition is final.
You can do 2.x version in a branch and 3.x on master branch
That way you can do a 2.x release from branch if you ever need to.

I would also like to add :

```
provides :newrelic_java_agent
```

To make Chef15+ happy

**Comment by djoos** [comment]
Hi @Sapr0,

I currently haven't got the bandwidth to make the changes for a 3.x version of the cookbook... If anyone is happy to work on this, I'd be more happy to pull it in on a 3.x branch though.

re: provides :newrelic_java_agent
Please send over a PR with all the provides of the cookbook and I'll review and merge it.

Hope this helps!

**Comment by zanecodes** [comment]
Out of curiosity, what's the motivation for exposing this functionality via resources rather than attribute-controlled recipes?
I see a number of cookbooks following a similar pattern, but it doesn't seem to make sense to me for most of them.

My mental model is that a _resource_ is something there can be more than one of on a given node, and it has some notion of [_identity_](https://docs.chef.io/custom_resources/#identity) which allows them to be distinguished and configured independently. So for instance, a _file_ resource makes perfect sense, since it has a single unique, canonical identity (its absolute canonicalized path on the filesystem). Similarly, a _registry_key_ resource makes sense as well, since it too has a single unique, canonical path in the registry, and you can have many of them configured to different values independently of one another on the same node.
This notion of identity is used by Chef to ensure a resource isn't configured more than once within a Chef run (e.g. two different cookbooks fighting to set the content of the same configuration file), which helps enforce idempotence and prevent flapping.

In the case of this cookbook, to the best of my knowledge it doesn't make sense to have more than one of, say, the New Relic Infrastructure Agent on any particular node. In fact, the [`newrelic_agent_infrastructure`](https://github.com/djoos-cookbooks/newrelic/blob/master/resources/agent_infrastructure.rb) resource does not appear to define any of its properties as a [`name_property`](https://docs.chef.io/custom_resources/#define-properties), meaning that the identity of the resource has no semantic meaning. This means that I could, intentionally or otherwise, write a cookbook that contains multiple uses of the `newrelic_agent_infrastructure` resource with different names, and because of this Chef would not give me any warnings. If the different resources also have different property values, then I will find that my cookbook sets up New Relic twice on every Chef client run; changing the configuration to the first resource's values and then back to the second one's. If this involves service restarts then I'll also be losing metrics as a result.

By only providing this functionality in the form of a recipe configured via attributes, this problem can at least be mitigated, if not prevented. While it is possibly to call a recipe more than once in one Chef client run, it takes more effort to cause each recipe to take on differing attribute values, at least if one is setting attributes the recommended way (via an `attributes.rb` file in a wrapper cookbook, or in a Policyfile or Chef environment). Since attributes are merged at the beginning of the Chef client run, multiple uses of the same recipe will be harmless, provided the recipe is idempotent. Additionally, Chef client will be able to issue a warning or error that multiple resources with the same name are defined, making it easy to fix if so desired.

Given all that, it makes me wonder why many cookbooks are opting to provide custom resources instead of recipes + attributes. It seems like a major footgun to me, and I don't really see any benefits to it, so I'd be interested in hearing what the benefits I'm not seeing are.

**Comment by jeffbyrnes** [comment]
I'm going to close this as something that didn't end up happening, and at this point, I'm not in a position to offer further assistance!

Feel free to run with it though.
