### ISSUE TITLE
Please provide way to specify restart command to service

### ISSUE THREAD

**Issue by et304383** [djoos-cookbooks/newrelic#250]
I want to be able to execute 

```
service httpd graceful
```

but since the service_action parameter of the newrelic_agent_php resource is passed directly to the service resource, I don't get a way to specify the restart command.  I'd like to be able to customize this.

Thanks!

**Comment by djoos** [comment]
Hi @eric-tucker,

would you be able to share how you're using the newrelic_agent_php currently?
You're passing service_name 'httpd' and service_action 'graceful', right?

Thanks in advance for your feedback!
David

**Comment by eric-tucker** [comment]
I be honest I forget exactly what I tried.  I ended up abandoning trying to restart httpd as part of the Newrelic install!

But I'd like to be able to pass in graceful as the service action.  :)

**Comment by djoos** [comment]
Hi @eric-tucker,

you should be able to pass in the service_action on the LWRP:

```
newrelic_agent_php 'Install' do  
  license '0000ffff0000ffff0000ffff0000ffff0000ffff'  
  service_name 'httpd'
  service_action 'graceful'
  config_file '/etc/php.d/newrelic.ini'  
end
```

Hope this helps!
David

**Comment by eric-tucker** [comment]
Thanks so much!  Is this published to the Supermarket?

**Comment by djoos** [comment]
Yep, FYI: the service_action-attribute has been on that LWRP for a while already, but I admit there are a lot of attributes...

Hope this helps!

**Comment by eric-tucker** [comment]
Ahh right - that's what I tried.  That's why it didn't work.  It's trying to pass "graceful" as the action to the service. Kind of like doing this:

```
service "httpd" do
  action :graceful
end
```

This does not work.  This is what I need to be able to accomplish:

```
service "httpd" do
  action :restart
  restart_command "service httpd graceful"
end
```

Now I remember why I opened this issue to begin with.  :)

**Comment by eric-tucker** [comment]
@djoos Can you please reopen this?

We need a way to specify the restart command.  I'm getting issues with newrelic issuing a restart command back to back with a restart command of httpd graceful and with these too close to each other back to back httpd craps out thinking that port 80 is in use:

```
[2016-11-03T15:39:03+00:00] INFO: execute[newrelic-install] sending restart action to service[httpd] (delayed)
[2016-11-03T15:39:03+00:00] INFO: Processing service[httpd] action restart (/etc/chef/local-mode-cache/cache/cookbooks/newrelic/providers/agent_php.rb line 86)
[2016-11-03T15:39:06+00:00] INFO: service[httpd] restarted
[2016-11-03T15:39:06+00:00] INFO: template[/etc/php.ini] sending restart action to service[httpd_graceful] (delayed)
[2016-11-03T15:39:06+00:00] INFO: Processing service[httpd_graceful] action restart (httpd_wrapper::default line 197)

================================================================================
Error executing action `restart` on resource 'service[httpd_graceful]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of service httpd graceful ----
STDOUT: Gracefully restarting httpd: httpd not running, trying to start
STDERR: (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
---- End output of service httpd graceful ----
Ran service httpd graceful returned 1
```

We NEVER use restart.  We always use graceful.  That's why I need the ability to specify the restart command.  Specifying the action to send to httpd isn't sufficient.

**Comment by djoos** [comment]
Quick braindump: doubting between opening up the service-resource within the cookbook for parameterization (in that case any attribute, including the restart_command, on the service-resource potentially has to be driven by the cookbook, which I'm not really in favor of) - or (leaning towards this option) - allowing you to define the service yourself (ie. in a wrapper cookbook or so) and suppress the cookbook from handling the service in `webserver_service` in the LWRP, but obviously still calling it in the notifies.

What are your thoughts?

**Comment by eric-tucker** [comment]
I think the resource should do exactly what it's supposed to and nothing more.  I don't think it should be doing restarts of httpd or trying to call other resources.  In my opinion, you're overloading this LWRP definition.  You've almost coded it half like a bloated recipe (no offence).

Keep your resource definition for newrelic_agent_php defined as doing exactly what it should do - install the agent.  If we have restart httpd afterwards, we'll do that in our cookbook which calls your resource.

As long as your LWRP supports notifies then we can put a notifies restart against our service.

I've already taken out defining a service name.  I don't even need this as I already have enough restarts of the httpd service as it is so the odds of me needing a restart of of httpd because of YOUR particular resource call are very small.  If it was needed, I'd just add a notifies as that's how I'd expect things to work.

A resource block touches something httpd needs to know about?  It notifies httpd with restart.

**Comment by djoos** [comment]
I agree, there's a lot of baggage in the LWRP. Definitely something that needs tackling in 3.x, but for now there's the "evolutionary" LWRP we've got...

Have you got the time to put a PR together? Happy to review it and get it merged in ASAP!

**Comment by eric-tucker** [comment]
Admittedly I don't have much experience with resources from pre Chef 12.5 using providers and libraries so it would be a while before I could offer up a PR.

If this was a straight resources folder only style cookbook maybe.  :)

**Comment by djoos** [comment]
Ah ok, no problem!
